### ISSUE TITLE
Image downloading permission issue.

### ISSUE THREAD

**Issue by AnujWebhopers** [ko2ic/image_downloader#102]
When I am trying to download images. after **permission** allows app crash. see logs below.

**Logs Detail:**

E/MethodChannel#plugins.ko2ic.com/image_downloader(30848): 	at io.flutter.embedding.android.FlutterActivity.onRequestPermissionsResult(FlutterActivity.java:640)
E/MethodChannel#plugins.ko2ic.com/image_downloader(30848): 	at android.app.Activity.requestPermissions(Activity.java:4542)
E/MethodChannel#plugins.ko2ic.com/image_downloader(30848): 	at androidx.core.app.ActivityCompat.requestPermissions(ActivityCompat.java:502)
E/MethodChannel#plugins.ko2ic.com/image_downloader(30848): 	at com.ko2ic.imagedownloader.ImageDownloaderPermissionListener.alreadyGranted(ImageDownloaderPermissionListener.kt:46)
E/MethodChannel#plugins.ko2ic.com/image_downloader(30848): 	at com.ko2ic.imagedownloader.ImageDownloaderPermissionListener.onRequestPermissionsResult(ImageDownloaderPermissionListener.kt:30)
E/MethodChannel#plugins.ko2ic.com/image_downloader(30848): 	at io.flutter.embedding.engine.FlutterEngineConnectionRegistry$FlutterEngineActivityPluginBinding.onRequestPermissionsResult(FlutterEngineConnectionRegistry.java:712)
E/MethodChannel#plugins.ko2ic.com/image_downloader(30848): 	at io.flutter.embedding.engine.FlutterEngineConnectionRegistry.onRequestPermissionsResult(FlutterEngineConnectionRegistry.java:412)
E/MethodChannel#plugins.ko2ic.com/image_downloader(30848): 	at io.flutter.embedding.android.FlutterActivityAndFragmentDelegate.onRequestPermissionsResult(FlutterActivityAndFragmentDelegate.java:627)
E/MethodChannel#plugins.ko2ic.com/image_downloader(30848): 	at io.flutter.embedding.android.FlutterActivity.onRequestPermissionsResult(FlutterActivity.java:640)
E/MethodChannel#plugins.ko2ic.com/image_downloader(30848): 	at android.app.Activity.requestPermissions(Activity.java:4542)

**Comment by ManuelBarrabino** [comment]
Same here on android!
