### ISSUE TITLE
App crashed on Android 10 caused by MIME type

### ISSUE THREAD

**Issue by windows7lake** [ko2ic/image_downloader#73]
D/image_downloader( 6855): 100
D/AndroidRuntime( 6855): Shutting down VM
E/AndroidRuntime( 6855): FATAL EXCEPTION: main
E/AndroidRuntime( 6855): Process: com.ko2ic.imagedownloader.example, PID: 6855
E/AndroidRuntime( 6855): java.lang.RuntimeException: Error receiving broadcast Intent { act=android.intent.action.DOWNLOAD_COMPLETE flg=0x10 pkg=com.ko2ic.imagedownloader.example (has extras) } in com.ko2ic.imagedownloader.Downloader$execute$1@d81a2b2
E/AndroidRuntime( 6855): 	at android.app.LoadedApk$ReceiverDispatcher$Args.lambda$getRunnable$0$LoadedApk$ReceiverDispatcher$Args(LoadedApk.java:1560)
E/AndroidRuntime( 6855): 	at android.app.-$$Lambda$LoadedApk$ReceiverDispatcher$Args$_BumDX2UKsnxLVrE6UJsJZkotuA.run(Unknown Source:2)
E/AndroidRuntime( 6855): 	at android.os.Handler.handleCallback(Handler.java:883)
E/AndroidRuntime( 6855): 	at android.os.Handler.dispatchMessage(Handler.java:100)
E/AndroidRuntime( 6855): 	at android.os.Looper.loop(Looper.java:214)
E/AndroidRuntime( 6855): 	at android.app.ActivityThread.main(ActivityThread.java:7356)
E/AndroidRuntime( 6855): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime( 6855): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
E/AndroidRuntime( 6855): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
E/AndroidRuntime( 6855): Caused by: java.lang.IllegalArgumentException: MIME type audio/x-wav cannot be inserted into content://media/external/images/media; expected MIME type under image/*
E/AndroidRuntime( 6855): 	at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:170)
E/AndroidRuntime( 6855): 	at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:140)
E/AndroidRuntime( 6855): 	at android.content.ContentProviderProxy.insert(ContentProviderNative.java:481)
E/AndroidRuntime( 6855): 	at android.content.ContentResolver.insert(ContentResolver.java:1828)
E/AndroidRuntime( 6855): 	at com.ko2ic.imagedownloader.ImageDownloaderPlugin$CallbackImpl.saveToDatabase(ImageDownloaderPlugin.kt:334)
E/AndroidRuntime( 6855): 	at com.ko2ic.imagedownloader.ImageDownloaderPlugin$CallbackImpl.access$saveToDatabase(ImageDownloaderPlugin.kt:200)
E/AndroidRuntime( 6855): 	at com.ko2ic.imagedownloader.ImageDownloaderPlugin$CallbackImpl$granted$3.invoke(ImageDownloaderPlugin.kt:301)
E/AndroidRuntime( 6855): 	at com.ko2ic.imagedownloader.ImageDownloaderPlugin$CallbackImpl$granted$3.invoke(ImageDownloaderPlugin.kt:200)
E/AndroidRuntime( 6855): 	at com.ko2ic.imagedownloader.Downloader.resolveDownloadStatus(Downloader.kt:171)
E/AndroidRuntime( 6855): 	at com.ko2ic.imagedownloader.Downloader.access$resolveDownloadStatus(Downloader.kt:14)
E/AndroidRuntime( 6855): 	at com.ko2ic.imagedownloader.Downloader$execute$1.onReceive(Downloader.kt:33)
E/AndroidRuntime( 6855): 	at android.app.LoadedApk$ReceiverDispatcher$Args.lambda$getRunnable$0$LoadedApk$ReceiverDispatcher$Args(LoadedApk.java:1550)
E/AndroidRuntime( 6855): 	... 8 more
I/Process ( 6855): Sending signal. PID: 6855 SIG: 9

download image link: https://images.debug.100.com.tw/service/2017/06/27/src_149854272953914708.jpg!t1500-v5.webp

**Comment by windows7lake** [comment]
fixed with [](https://github.com/ko2ic/image_downloader/pull/74)
